import { /*Geist, Geist_Mono,*/ Outfit } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "../context/AppContext";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({ subsets: ['latin'], weight: ["300","400","500" ] })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
      //  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      className={`${outfit.className} antialiased text-gray-700`}
      >
        <Toaster />
        <AppContextProvider>
         {children}
        </AppContextProvider>      
      </body>
    </html>
    </ClerkProvider>
  );
}
